[project]
name = "option-binomial-pricing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "molinamath", email = "molina.matheust@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
option-binomial-pricing = "option_binomial_pricing:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
